name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest utest_iso20022_generator.py

    - name: Run system tests
      run: |
        python -m unittest stest_iso20022_generator.py

    - name: Upload pipeline log
      if: always()  # ensures this step runs even if previous steps fail
      uses: actions/upload-artifact@v3
      with:
        name: pipeline-log
        path: pipeline_log.txt
