name: Run PACS.008 Tests and Generate HTML Log

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml

    - name: Run utest.py and stest.py
      run: |
        echo "Running utest.py..."
        python utest.py
        echo "Running stest.py..."
        python stest.py

    - name: List files for debugging
      run: ls -la

    - name: Upload HTML log
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-log-html
        path: pipeline_log.html
