name: Run PACS.008 Tests and Generate HTML Log

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml

    - name: Run tests and save log
      run: |
        echo "Running tests..."
        python -m unittest discover > pipeline_log.txt 2>&1

    - name: Convert log to HTML
      run: |
        echo "Converting log to HTML..."
        echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Pipeline Log</title><style>body{font-family:Arial;}pre{background:#f4f4f4;padding:10px;border:1px solid #ccc;}</style></head><body><h1>Pipeline Log</h1><pre>" > pipeline_log.html
        cat pipeline_log.txt >> pipeline_log.html
        echo "</pre></body></html>" >> pipeline_log.html

    - name: Upload HTML log
      uses: actions/upload-artifact@v3
      with:
        name: pipeline-log-html
        path: pipeline_log.html
